name: emetshaf
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-48.0.dev <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  flex_color_picker: ^3.2.2
  flex_color_scheme: ^7.0.5
  flex_seed_scheme: ^1.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_cache_manager: ^3.3.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.4
  http: ^0.13.6
  intl: ^0.18.1
  path_provider: ^2.0.15
  path_provider_android: ^2.0.27
  path_provider_foundation: ^2.2.3
  path_provider_platform_interface: ^2.0.6
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  shared_preferences_android: ^2.1.4
  shared_preferences_ios: ^2.1.1
  shared_preferences_platform_interface: ^2.2.0
  shared_preferences_web: ^2.1.0
  sqflite: ^2.2.8+3
  url_launcher: ^6.1.11
  url_launcher_android: ^6.0.33
  url_launcher_ios: ^6.1.4
  url_launcher_platform_interface: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  # dart run intl_utils:generate
  intl_utils: ^2.8.2

flutter_intl:
  enabled: true
  class_name: L10n
  main_locale: en
  arb_dir: lib/src/l10n
  output_dir: lib/src/generated

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
